title: "Itzel Casta√±eda"
email: "ic28@rice.edu"
tagline: "Caminante, no hay camino, se hace camino al andar."
repository: itzelcastaneda/itzelcastaneda.github.io
url: "https://itzelcastaneda.github.io"
baseurl: "/pages/itzelcastaneda/"
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
